#[repr(u8)]
#[allow(unused)]
#[derive(Clone, Copy, PartialEq, PartialOrd, Debug)]
pub enum Key {
    Escape,
    Tab,
    Enter,
    ArrowUp,
    Backspace,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    LeftAlt,
    LeftShift,
    RightAlt,
    RightShift,
    LeftCtrl,
    RightCtrl,
    CapsLock,
    NumLock,
    ScrollLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    N0,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,
    Point,
    Space,
    Equal,
    Comma,
    Backtick,
    Semicolon,
    Backslash,
    SingleQuote,
    SquareBracketsOpen,
    SquareBracketsClosed,
    Add,
    Sub,
    Mul,
    Div,
}

#[derive(Debug, Copy, Clone)]
pub enum Event {
    Pressed,
    Released,
}

#[derive(Debug, Copy, Clone)]
pub struct KeyEvent {
    key: Key,
    event: Event,
    scancode: u8,
}

impl KeyEvent {
    pub const fn new(scancode: u8, event: Event, key: Key) -> Self {
        Self { key, event, scancode }
    }
}
use Event::*;
use Key::*;

/// Conversion table for all characters currently supported by our kernel for
/// PS2 input.
///
/// https://wiki.osdev.org/PS/2_Keyboard#Scan_Code_Set_1
pub const SCANCODE_SET_1_TO_KEY: [Option<KeyEvent>; 256] = [
    None,
    Some(KeyEvent::new(0x01, Pressed, Escape)),
    Some(KeyEvent::new(0x02, Pressed, N1)),
    Some(KeyEvent::new(0x03, Pressed, N2)),
    Some(KeyEvent::new(0x04, Pressed, N3)),
    Some(KeyEvent::new(0x05, Pressed, N4)),
    Some(KeyEvent::new(0x06, Pressed, N5)),
    Some(KeyEvent::new(0x07, Pressed, N6)),
    Some(KeyEvent::new(0x08, Pressed, N7)),
    Some(KeyEvent::new(0x09, Pressed, N8)),
    Some(KeyEvent::new(0x0a, Pressed, N9)),
    Some(KeyEvent::new(0x0b, Pressed, N0)),
    Some(KeyEvent::new(0x0c, Pressed, Sub)),
    Some(KeyEvent::new(0x0d, Pressed, Equal)),
    Some(KeyEvent::new(0x0e, Pressed, Backspace)),
    Some(KeyEvent::new(0x0f, Pressed, Tab)),
    Some(KeyEvent::new(0x10, Pressed, Q)),
    Some(KeyEvent::new(0x11, Pressed, W)),
    Some(KeyEvent::new(0x12, Pressed, E)),
    Some(KeyEvent::new(0x13, Pressed, R)),
    Some(KeyEvent::new(0x14, Pressed, T)),
    Some(KeyEvent::new(0x15, Pressed, Y)),
    Some(KeyEvent::new(0x16, Pressed, U)),
    Some(KeyEvent::new(0x17, Pressed, I)),
    Some(KeyEvent::new(0x18, Pressed, O)),
    Some(KeyEvent::new(0x19, Pressed, P)),
    Some(KeyEvent::new(0x1a, Pressed, SquareBracketsOpen)),
    Some(KeyEvent::new(0x1b, Pressed, SquareBracketsClosed)),
    Some(KeyEvent::new(0x1c, Pressed, Enter)),
    Some(KeyEvent::new(0x1d, Pressed, LeftCtrl)),
    Some(KeyEvent::new(0x1e, Pressed, A)),
    Some(KeyEvent::new(0x1f, Pressed, S)),
    Some(KeyEvent::new(0x20, Pressed, D)),
    Some(KeyEvent::new(0x21, Pressed, F)),
    Some(KeyEvent::new(0x22, Pressed, G)),
    Some(KeyEvent::new(0x23, Pressed, H)),
    Some(KeyEvent::new(0x24, Pressed, J)),
    Some(KeyEvent::new(0x25, Pressed, K)),
    Some(KeyEvent::new(0x26, Pressed, L)),
    Some(KeyEvent::new(0x27, Pressed, Semicolon)),
    Some(KeyEvent::new(0x28, Pressed, SingleQuote)),
    Some(KeyEvent::new(0x29, Pressed, Backtick)),
    Some(KeyEvent::new(0x2a, Pressed, LeftShift)),
    Some(KeyEvent::new(0x2b, Pressed, Backslash)),
    Some(KeyEvent::new(0x2c, Pressed, Z)),
    Some(KeyEvent::new(0x2d, Pressed, X)),
    Some(KeyEvent::new(0x2e, Pressed, C)),
    Some(KeyEvent::new(0x2f, Pressed, V)),
    Some(KeyEvent::new(0x30, Pressed, B)),
    Some(KeyEvent::new(0x31, Pressed, N)),
    Some(KeyEvent::new(0x32, Pressed, M)),
    Some(KeyEvent::new(0x33, Pressed, Comma)),
    Some(KeyEvent::new(0x34, Pressed, Point)),
    Some(KeyEvent::new(0x35, Pressed, Div)),
    Some(KeyEvent::new(0x36, Pressed, RightShift)),
    Some(KeyEvent::new(0x37, Pressed, Mul)),
    Some(KeyEvent::new(0x38, Pressed, LeftAlt)),
    Some(KeyEvent::new(0x39, Pressed, Space)),
    Some(KeyEvent::new(0x3a, Pressed, CapsLock)),
    Some(KeyEvent::new(0x3b, Pressed, F1)),
    Some(KeyEvent::new(0x3c, Pressed, F2)),
    Some(KeyEvent::new(0x3d, Pressed, F3)),
    Some(KeyEvent::new(0x3e, Pressed, F4)),
    Some(KeyEvent::new(0x3f, Pressed, F5)),
    Some(KeyEvent::new(0x40, Pressed, F6)),
    Some(KeyEvent::new(0x41, Pressed, F7)),
    Some(KeyEvent::new(0x42, Pressed, F8)),
    Some(KeyEvent::new(0x43, Pressed, F9)),
    Some(KeyEvent::new(0x44, Pressed, F10)),
    Some(KeyEvent::new(0x45, Pressed, NumLock)),
    Some(KeyEvent::new(0x46, Pressed, ScrollLock)),
    Some(KeyEvent::new(0x47, Pressed, N7)),
    Some(KeyEvent::new(0x48, Pressed, N8)),
    Some(KeyEvent::new(0x49, Pressed, N9)),
    Some(KeyEvent::new(0x4a, Pressed, Sub)),
    Some(KeyEvent::new(0x4b, Pressed, N4)),
    Some(KeyEvent::new(0x4c, Pressed, N5)),
    Some(KeyEvent::new(0x4d, Pressed, N6)),
    Some(KeyEvent::new(0x4e, Pressed, Add)),
    Some(KeyEvent::new(0x4f, Pressed, N1)),
    Some(KeyEvent::new(0x50, Pressed, N2)),
    Some(KeyEvent::new(0x51, Pressed, N3)),
    Some(KeyEvent::new(0x52, Pressed, N0)),
    Some(KeyEvent::new(0x53, Pressed, Point)),
    None,
    None,
    None,
    Some(KeyEvent::new(0x57, Pressed, F11)),
    Some(KeyEvent::new(0x58, Pressed, F12)),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(KeyEvent::new(0x81, Released, Escape)),
    Some(KeyEvent::new(0x82, Released, N1)),
    Some(KeyEvent::new(0x83, Released, N2)),
    Some(KeyEvent::new(0x84, Released, N3)),
    Some(KeyEvent::new(0x85, Released, N4)),
    Some(KeyEvent::new(0x86, Released, N5)),
    Some(KeyEvent::new(0x87, Released, N6)),
    Some(KeyEvent::new(0x88, Released, N7)),
    Some(KeyEvent::new(0x89, Released, N8)),
    Some(KeyEvent::new(0x8a, Released, N9)),
    Some(KeyEvent::new(0x8b, Released, N0)),
    Some(KeyEvent::new(0x8c, Released, Sub)),
    Some(KeyEvent::new(0x8d, Released, Equal)),
    Some(KeyEvent::new(0x8e, Released, Backspace)),
    Some(KeyEvent::new(0x8f, Released, Tab)),
    Some(KeyEvent::new(0x90, Released, Q)),
    Some(KeyEvent::new(0x91, Released, W)),
    Some(KeyEvent::new(0x92, Released, E)),
    Some(KeyEvent::new(0x93, Released, R)),
    Some(KeyEvent::new(0x94, Released, T)),
    Some(KeyEvent::new(0x95, Released, Y)),
    Some(KeyEvent::new(0x96, Released, U)),
    Some(KeyEvent::new(0x97, Released, I)),
    Some(KeyEvent::new(0x98, Released, O)),
    Some(KeyEvent::new(0x99, Released, P)),
    Some(KeyEvent::new(0x9a, Released, SquareBracketsOpen)),
    Some(KeyEvent::new(0x9b, Released, SquareBracketsClosed)),
    Some(KeyEvent::new(0x9c, Released, Enter)),
    Some(KeyEvent::new(0x9d, Released, LeftCtrl)),
    Some(KeyEvent::new(0x9e, Released, A)),
    Some(KeyEvent::new(0x9f, Released, S)),
    Some(KeyEvent::new(0xa0, Released, D)),
    Some(KeyEvent::new(0xa1, Released, F)),
    Some(KeyEvent::new(0xa2, Released, G)),
    Some(KeyEvent::new(0xa3, Released, H)),
    Some(KeyEvent::new(0xa4, Released, J)),
    Some(KeyEvent::new(0xa5, Released, K)),
    Some(KeyEvent::new(0xa6, Released, L)),
    Some(KeyEvent::new(0xa7, Released, Semicolon)),
    Some(KeyEvent::new(0xa8, Released, SingleQuote)),
    Some(KeyEvent::new(0xa9, Released, Backtick)),
    Some(KeyEvent::new(0xaa, Released, LeftShift)),
    Some(KeyEvent::new(0xab, Released, Backslash)),
    Some(KeyEvent::new(0xac, Released, Z)),
    Some(KeyEvent::new(0xad, Released, X)),
    Some(KeyEvent::new(0xae, Released, C)),
    Some(KeyEvent::new(0xaf, Released, V)),
    Some(KeyEvent::new(0xb0, Released, B)),
    Some(KeyEvent::new(0xb1, Released, N)),
    Some(KeyEvent::new(0xb2, Released, M)),
    Some(KeyEvent::new(0xb3, Released, Comma)),
    Some(KeyEvent::new(0xb4, Released, Point)),
    Some(KeyEvent::new(0xb5, Released, Div)),
    Some(KeyEvent::new(0xb6, Released, RightShift)),
    Some(KeyEvent::new(0xb7, Released, Mul)),
    Some(KeyEvent::new(0xb8, Released, LeftAlt)),
    Some(KeyEvent::new(0xb9, Released, Space)),
    Some(KeyEvent::new(0xba, Released, CapsLock)),
    Some(KeyEvent::new(0xbb, Released, F1)),
    Some(KeyEvent::new(0xbc, Released, F2)),
    Some(KeyEvent::new(0xbd, Released, F3)),
    Some(KeyEvent::new(0xbe, Released, F4)),
    Some(KeyEvent::new(0xbf, Released, F5)),
    Some(KeyEvent::new(0xc0, Released, F6)),
    Some(KeyEvent::new(0xc1, Released, F7)),
    Some(KeyEvent::new(0xc2, Released, F8)),
    Some(KeyEvent::new(0xc3, Released, F9)),
    Some(KeyEvent::new(0xc4, Released, F10)),
    Some(KeyEvent::new(0xc5, Released, NumLock)),
    Some(KeyEvent::new(0xc6, Released, ScrollLock)),
    Some(KeyEvent::new(0xc7, Released, N7)),
    Some(KeyEvent::new(0xc8, Released, N8)),
    Some(KeyEvent::new(0xc9, Released, N9)),
    Some(KeyEvent::new(0xca, Released, Sub)),
    Some(KeyEvent::new(0xcb, Released, N4)),
    Some(KeyEvent::new(0xcc, Released, N5)),
    Some(KeyEvent::new(0xcd, Released, N6)),
    Some(KeyEvent::new(0xce, Released, Add)),
    Some(KeyEvent::new(0xcf, Released, N1)),
    Some(KeyEvent::new(0xd0, Released, N2)),
    Some(KeyEvent::new(0xd1, Released, N3)),
    Some(KeyEvent::new(0xd2, Released, N0)),
    None,
    None,
    None,
    None,
    Some(KeyEvent::new(0xd7, Released, F11)),
    Some(KeyEvent::new(0xd8, Released, F12)),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
];

pub const SCANCODE_SET_1_TO_KEY_EXTENDED: [Option<KeyEvent>; 256] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(KeyEvent::new(0x48, Pressed, ArrowUp)),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(KeyEvent::new(0x50, Pressed, ArrowDown)),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
];
