#[derive(Clone, Copy, Debug)]
pub enum Key {
    Escape,
    Tab,
    Enter,
    ArrowUp,
    Backspace,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    LeftAlt,
    RightAlt,
    LeftShift,
    RightShift,
    LeftCtrl,
    RightCtrl,
    LeftGui,
    RightGui,
    CapsLock,
    NumLock,
    ScrollLock,
    Minus,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    N0,
    N1,
    N2,
    N3,
    N4,
    N5,
    N6,
    N7,
    N8,
    N9,
    Point,
    Space,
    Equal,
    Comma,
    Backtick,
    Semicolon,
    Slash,
    Backslash,
    SingleQuote,
    SquareBracketsOpen,
    SquareBracketsClosed,
    KeypadAdd,
    KeypadSub,
    KeypadMul,
    KeypadDiv,
    KeypadEnter,
    KeypadN0,
    KeypadN1,
    KeypadN2,
    KeypadN3,
    KeypadN4,
    KeypadN5,
    KeypadN6,
    KeypadN7,
    KeypadN8,
    KeypadN9,
    KeypadComma,
}

#[derive(Debug, Copy, Clone)]
pub enum Event {
    Pressed,
    Released,
}

#[derive(Debug, Copy, Clone)]
pub struct KeyEvent {
    pub key: Key,
    pub event: Event,
    pub scancode: u8,
}

impl KeyEvent {
    pub const fn new(scancode: u8, event: Event, key: Key) -> Self {
        Self { key, event, scancode }
    }
}
use Event::*;
use Key::*;

/// Conversion table for all characters currently supported by our kernel for
/// PS2 input.
///
/// https://wiki.osdev.org/PS/2_Keyboard#Scan_Code_Set_1
pub const SCANCODE_SET_1_TO_KEY: [Option<KeyEvent>; 256] = [
    /* 0x00 */ None,
    /* 0x01 */ Some(KeyEvent::new(0x01, Pressed, Escape)),
    /* 0x02 */ Some(KeyEvent::new(0x02, Pressed, N1)),
    /* 0x03 */ Some(KeyEvent::new(0x03, Pressed, N2)),
    /* 0x04 */ Some(KeyEvent::new(0x04, Pressed, N3)),
    /* 0x05 */ Some(KeyEvent::new(0x05, Pressed, N4)),
    /* 0x06 */ Some(KeyEvent::new(0x06, Pressed, N5)),
    /* 0x07 */ Some(KeyEvent::new(0x07, Pressed, N6)),
    /* 0x08 */ Some(KeyEvent::new(0x08, Pressed, N7)),
    /* 0x09 */ Some(KeyEvent::new(0x09, Pressed, N8)),
    /* 0x0a */ Some(KeyEvent::new(0x0a, Pressed, N9)),
    /* 0x0b */ Some(KeyEvent::new(0x0b, Pressed, N0)),
    /* 0x0c */ Some(KeyEvent::new(0x0c, Pressed, Minus)),
    /* 0x0d */ Some(KeyEvent::new(0x0d, Pressed, Equal)),
    /* 0x0e */ Some(KeyEvent::new(0x0e, Pressed, Backspace)),
    /* 0x0f */ Some(KeyEvent::new(0x0f, Pressed, Tab)),
    /* 0x10 */ Some(KeyEvent::new(0x10, Pressed, Q)),
    /* 0x11 */ Some(KeyEvent::new(0x11, Pressed, W)),
    /* 0x12 */ Some(KeyEvent::new(0x12, Pressed, E)),
    /* 0x13 */ Some(KeyEvent::new(0x13, Pressed, R)),
    /* 0x14 */ Some(KeyEvent::new(0x14, Pressed, T)),
    /* 0x15 */ Some(KeyEvent::new(0x15, Pressed, Y)),
    /* 0x16 */ Some(KeyEvent::new(0x16, Pressed, U)),
    /* 0x17 */ Some(KeyEvent::new(0x17, Pressed, I)),
    /* 0x18 */ Some(KeyEvent::new(0x18, Pressed, O)),
    /* 0x19 */ Some(KeyEvent::new(0x19, Pressed, P)),
    /* 0x1a */ Some(KeyEvent::new(0x1a, Pressed, SquareBracketsOpen)),
    /* 0x1b */ Some(KeyEvent::new(0x1b, Pressed, SquareBracketsClosed)),
    /* 0x1c */ Some(KeyEvent::new(0x1c, Pressed, Enter)),
    /* 0x1d */ Some(KeyEvent::new(0x1d, Pressed, LeftCtrl)),
    /* 0x1e */ Some(KeyEvent::new(0x1e, Pressed, A)),
    /* 0x1f */ Some(KeyEvent::new(0x1f, Pressed, S)),
    /* 0x20 */ Some(KeyEvent::new(0x20, Pressed, D)),
    /* 0x21 */ Some(KeyEvent::new(0x21, Pressed, F)),
    /* 0x22 */ Some(KeyEvent::new(0x22, Pressed, G)),
    /* 0x23 */ Some(KeyEvent::new(0x23, Pressed, H)),
    /* 0x24 */ Some(KeyEvent::new(0x24, Pressed, J)),
    /* 0x25 */ Some(KeyEvent::new(0x25, Pressed, K)),
    /* 0x26 */ Some(KeyEvent::new(0x26, Pressed, L)),
    /* 0x27 */ Some(KeyEvent::new(0x27, Pressed, Semicolon)),
    /* 0x28 */ Some(KeyEvent::new(0x28, Pressed, SingleQuote)),
    /* 0x29 */ Some(KeyEvent::new(0x29, Pressed, Backtick)),
    /* 0x2a */ Some(KeyEvent::new(0x2a, Pressed, LeftShift)),
    /* 0x2b */ Some(KeyEvent::new(0x2b, Pressed, Backslash)),
    /* 0x2c */ Some(KeyEvent::new(0x2c, Pressed, Z)),
    /* 0x2d */ Some(KeyEvent::new(0x2d, Pressed, X)),
    /* 0x2e */ Some(KeyEvent::new(0x2e, Pressed, C)),
    /* 0x2f */ Some(KeyEvent::new(0x2f, Pressed, V)),
    /* 0x30 */ Some(KeyEvent::new(0x30, Pressed, B)),
    /* 0x31 */ Some(KeyEvent::new(0x31, Pressed, N)),
    /* 0x32 */ Some(KeyEvent::new(0x32, Pressed, M)),
    /* 0x33 */ Some(KeyEvent::new(0x33, Pressed, Comma)),
    /* 0x34 */ Some(KeyEvent::new(0x34, Pressed, Point)),
    /* 0x35 */ Some(KeyEvent::new(0x35, Pressed, Slash)),
    /* 0x36 */ Some(KeyEvent::new(0x36, Pressed, RightShift)),
    /* 0x37 */ Some(KeyEvent::new(0x37, Pressed, KeypadMul)),
    /* 0x38 */ Some(KeyEvent::new(0x38, Pressed, LeftAlt)),
    /* 0x39 */ Some(KeyEvent::new(0x39, Pressed, Space)),
    /* 0x3a */ Some(KeyEvent::new(0x3a, Pressed, CapsLock)),
    /* 0x3b */ Some(KeyEvent::new(0x3b, Pressed, F1)),
    /* 0x3c */ Some(KeyEvent::new(0x3c, Pressed, F2)),
    /* 0x3d */ Some(KeyEvent::new(0x3d, Pressed, F3)),
    /* 0x3e */ Some(KeyEvent::new(0x3e, Pressed, F4)),
    /* 0x3f */ Some(KeyEvent::new(0x3f, Pressed, F5)),
    /* 0x40 */ Some(KeyEvent::new(0x40, Pressed, F6)),
    /* 0x41 */ Some(KeyEvent::new(0x41, Pressed, F7)),
    /* 0x42 */ Some(KeyEvent::new(0x42, Pressed, F8)),
    /* 0x43 */ Some(KeyEvent::new(0x43, Pressed, F9)),
    /* 0x44 */ Some(KeyEvent::new(0x44, Pressed, F10)),
    /* 0x45 */ Some(KeyEvent::new(0x45, Pressed, NumLock)),
    /* 0x46 */ Some(KeyEvent::new(0x46, Pressed, ScrollLock)),
    /* 0x47 */ Some(KeyEvent::new(0x47, Pressed, KeypadN7)),
    /* 0x48 */ Some(KeyEvent::new(0x48, Pressed, KeypadN8)),
    /* 0x49 */ Some(KeyEvent::new(0x49, Pressed, KeypadN9)),
    /* 0x4a */ Some(KeyEvent::new(0x4a, Pressed, KeypadSub)),
    /* 0x4b */ Some(KeyEvent::new(0x4b, Pressed, KeypadN4)),
    /* 0x4c */ Some(KeyEvent::new(0x4c, Pressed, KeypadN5)),
    /* 0x4d */ Some(KeyEvent::new(0x4d, Pressed, KeypadN6)),
    /* 0x4e */ Some(KeyEvent::new(0x4e, Pressed, KeypadAdd)),
    /* 0x4f */ Some(KeyEvent::new(0x4f, Pressed, KeypadN1)),
    /* 0x50 */ Some(KeyEvent::new(0x50, Pressed, KeypadN2)),
    /* 0x51 */ Some(KeyEvent::new(0x51, Pressed, KeypadN3)),
    /* 0x52 */ Some(KeyEvent::new(0x52, Pressed, KeypadN0)),
    /* 0x53 */ Some(KeyEvent::new(0x53, Pressed, KeypadComma)),
    /* 0x54 */ None,
    /* 0x55 */ None,
    /* 0x56 */ None,
    /* 0x57 */ Some(KeyEvent::new(0x57, Pressed, F11)),
    /* 0x58 */ Some(KeyEvent::new(0x58, Pressed, F12)),
    /* 0x59 */ None,
    /* 0x5a */ None,
    /* 0x5b */ None,
    /* 0x5c */ None,
    /* 0x5d */ None,
    /* 0x5e */ None,
    /* 0x5f */ None,
    /* 0x60 */ None,
    /* 0x61 */ None,
    /* 0x62 */ None,
    /* 0x63 */ None,
    /* 0x64 */ None,
    /* 0x65 */ None,
    /* 0x66 */ None,
    /* 0x67 */ None,
    /* 0x68 */ None,
    /* 0x69 */ None,
    /* 0x6a */ None,
    /* 0x6b */ None,
    /* 0x6c */ None,
    /* 0x6d */ None,
    /* 0x6e */ None,
    /* 0x6f */ None,
    /* 0x70 */ None,
    /* 0x71 */ None,
    /* 0x72 */ None,
    /* 0x73 */ None,
    /* 0x74 */ None,
    /* 0x75 */ None,
    /* 0x76 */ None,
    /* 0x77 */ None,
    /* 0x78 */ None,
    /* 0x79 */ None,
    /* 0x7a */ None,
    /* 0x7b */ None,
    /* 0x7c */ None,
    /* 0x7d */ None,
    /* 0x7e */ None,
    /* 0x7f */ None,
    /* 0x80 */ None,
    /* 0x81 */ Some(KeyEvent::new(0x81, Released, Escape)),
    /* 0x82 */ Some(KeyEvent::new(0x82, Released, N1)),
    /* 0x83 */ Some(KeyEvent::new(0x83, Released, N2)),
    /* 0x84 */ Some(KeyEvent::new(0x84, Released, N3)),
    /* 0x85 */ Some(KeyEvent::new(0x85, Released, N4)),
    /* 0x86 */ Some(KeyEvent::new(0x86, Released, N5)),
    /* 0x87 */ Some(KeyEvent::new(0x87, Released, N6)),
    /* 0x88 */ Some(KeyEvent::new(0x88, Released, N7)),
    /* 0x89 */ Some(KeyEvent::new(0x89, Released, N8)),
    /* 0x8a */ Some(KeyEvent::new(0x8a, Released, N9)),
    /* 0x8b */ Some(KeyEvent::new(0x8b, Released, N0)),
    /* 0x8c */ Some(KeyEvent::new(0x8c, Released, Minus)),
    /* 0x8d */ Some(KeyEvent::new(0x8d, Released, Equal)),
    /* 0x8e */ Some(KeyEvent::new(0x8e, Released, Backspace)),
    /* 0x8f */ Some(KeyEvent::new(0x8f, Released, Tab)),
    /* 0x90 */ Some(KeyEvent::new(0x90, Released, Q)),
    /* 0x91 */ Some(KeyEvent::new(0x91, Released, W)),
    /* 0x92 */ Some(KeyEvent::new(0x92, Released, E)),
    /* 0x93 */ Some(KeyEvent::new(0x93, Released, R)),
    /* 0x94 */ Some(KeyEvent::new(0x94, Released, T)),
    /* 0x95 */ Some(KeyEvent::new(0x95, Released, Y)),
    /* 0x96 */ Some(KeyEvent::new(0x96, Released, U)),
    /* 0x97 */ Some(KeyEvent::new(0x97, Released, I)),
    /* 0x98 */ Some(KeyEvent::new(0x98, Released, O)),
    /* 0x99 */ Some(KeyEvent::new(0x99, Released, P)),
    /* 0x9a */ Some(KeyEvent::new(0x9a, Released, SquareBracketsOpen)),
    /* 0x9b */ Some(KeyEvent::new(0x9b, Released, SquareBracketsClosed)),
    /* 0x9c */ Some(KeyEvent::new(0x9c, Released, Enter)),
    /* 0x9d */ Some(KeyEvent::new(0x9d, Released, LeftCtrl)),
    /* 0x9e */ Some(KeyEvent::new(0x9e, Released, A)),
    /* 0x9f */ Some(KeyEvent::new(0x9f, Released, S)),
    /* 0xa0 */ Some(KeyEvent::new(0xa0, Released, D)),
    /* 0xa1 */ Some(KeyEvent::new(0xa1, Released, F)),
    /* 0xa2 */ Some(KeyEvent::new(0xa2, Released, G)),
    /* 0xa3 */ Some(KeyEvent::new(0xa3, Released, H)),
    /* 0xa4 */ Some(KeyEvent::new(0xa4, Released, J)),
    /* 0xa5 */ Some(KeyEvent::new(0xa5, Released, K)),
    /* 0xa6 */ Some(KeyEvent::new(0xa6, Released, L)),
    /* 0xa7 */ Some(KeyEvent::new(0xa7, Released, Semicolon)),
    /* 0xa8 */ Some(KeyEvent::new(0xa8, Released, SingleQuote)),
    /* 0xa9 */ Some(KeyEvent::new(0xa9, Released, Backtick)),
    /* 0xaa */ Some(KeyEvent::new(0xaa, Released, LeftShift)),
    /* 0xab */ Some(KeyEvent::new(0xab, Released, Backslash)),
    /* 0xac */ Some(KeyEvent::new(0xac, Released, Z)),
    /* 0xad */ Some(KeyEvent::new(0xad, Released, X)),
    /* 0xae */ Some(KeyEvent::new(0xae, Released, C)),
    /* 0xaf */ Some(KeyEvent::new(0xaf, Released, V)),
    /* 0xb0 */ Some(KeyEvent::new(0xb0, Released, B)),
    /* 0xb1 */ Some(KeyEvent::new(0xb1, Released, N)),
    /* 0xb2 */ Some(KeyEvent::new(0xb2, Released, M)),
    /* 0xb3 */ Some(KeyEvent::new(0xb3, Released, Comma)),
    /* 0xb4 */ Some(KeyEvent::new(0xb4, Released, Point)),
    /* 0xb5 */ Some(KeyEvent::new(0xb5, Released, Slash)),
    /* 0xb6 */ Some(KeyEvent::new(0xb6, Released, RightShift)),
    /* 0xb7 */ Some(KeyEvent::new(0xb7, Released, KeypadMul)),
    /* 0xb8 */ Some(KeyEvent::new(0xb8, Released, LeftAlt)),
    /* 0xb9 */ Some(KeyEvent::new(0xb9, Released, Space)),
    /* 0xba */ Some(KeyEvent::new(0xba, Released, CapsLock)),
    /* 0xbb */ Some(KeyEvent::new(0xbb, Released, F1)),
    /* 0xbc */ Some(KeyEvent::new(0xbc, Released, F2)),
    /* 0xbd */ Some(KeyEvent::new(0xbd, Released, F3)),
    /* 0xbe */ Some(KeyEvent::new(0xbe, Released, F4)),
    /* 0xbf */ Some(KeyEvent::new(0xbf, Released, F5)),
    /* 0xc0 */ Some(KeyEvent::new(0xc0, Released, F6)),
    /* 0xc1 */ Some(KeyEvent::new(0xc1, Released, F7)),
    /* 0xc2 */ Some(KeyEvent::new(0xc2, Released, F8)),
    /* 0xc3 */ Some(KeyEvent::new(0xc3, Released, F9)),
    /* 0xc4 */ Some(KeyEvent::new(0xc4, Released, F10)),
    /* 0xc5 */ Some(KeyEvent::new(0xc5, Released, NumLock)),
    /* 0xc6 */ Some(KeyEvent::new(0xc6, Released, ScrollLock)),
    /* 0xc7 */ Some(KeyEvent::new(0xc7, Released, KeypadN7)),
    /* 0xc8 */ Some(KeyEvent::new(0xc8, Released, KeypadN8)),
    /* 0xc9 */ Some(KeyEvent::new(0xc9, Released, KeypadN9)),
    /* 0xca */ Some(KeyEvent::new(0xca, Released, KeypadSub)),
    /* 0xcb */ Some(KeyEvent::new(0xcb, Released, KeypadN4)),
    /* 0xcc */ Some(KeyEvent::new(0xcc, Released, KeypadN5)),
    /* 0xcd */ Some(KeyEvent::new(0xcd, Released, KeypadN6)),
    /* 0xce */ Some(KeyEvent::new(0xce, Released, KeypadAdd)),
    /* 0xcf */ Some(KeyEvent::new(0xcf, Released, KeypadN1)),
    /* 0xd0 */ Some(KeyEvent::new(0xd0, Released, KeypadN2)),
    /* 0xd1 */ Some(KeyEvent::new(0xd1, Released, KeypadN3)),
    /* 0xd2 */ Some(KeyEvent::new(0xd2, Released, KeypadN0)),
    /* 0xd3 */ Some(KeyEvent::new(0xd3, Released, KeypadComma)),
    /* 0xd4 */ None,
    /* 0xd5 */ None,
    /* 0xd6 */ None,
    /* 0xd7 */ Some(KeyEvent::new(0xd7, Released, F11)),
    /* 0xd8 */ Some(KeyEvent::new(0xd8, Released, F12)),
    /* 0xd9 */ None,
    /* 0xda */ None,
    /* 0xdb */ None,
    /* 0xdc */ None,
    /* 0xdd */ None,
    /* 0xde */ None,
    /* 0xdf */ None,
    /* 0xe0 */ None,
    /* 0xe1 */ None,
    /* 0xe2 */ None,
    /* 0xe3 */ None,
    /* 0xe4 */ None,
    /* 0xe5 */ None,
    /* 0xe6 */ None,
    /* 0xe7 */ None,
    /* 0xe8 */ None,
    /* 0xe9 */ None,
    /* 0xea */ None,
    /* 0xeb */ None,
    /* 0xec */ None,
    /* 0xed */ None,
    /* 0xee */ None,
    /* 0xef */ None,
    /* 0xf0 */ None,
    /* 0xf1 */ None,
    /* 0xf2 */ None,
    /* 0xf3 */ None,
    /* 0xf4 */ None,
    /* 0xf5 */ None,
    /* 0xf6 */ None,
    /* 0xf7 */ None,
    /* 0xf8 */ None,
    /* 0xf9 */ None,
    /* 0xfa */ None,
    /* 0xfb */ None,
    /* 0xfc */ None,
    /* 0xfd */ None,
    /* 0xfe */ None,
    /* 0xff */ None,
];

pub const SCANCODE_SET_1_TO_KEY_EXTENDED: [Option<KeyEvent>; 256] = [
    /* 0x00 */ None,
    /* 0x01 */ None,
    /* 0x02 */ None,
    /* 0x03 */ None,
    /* 0x04 */ None,
    /* 0x05 */ None,
    /* 0x06 */ None,
    /* 0x07 */ None,
    /* 0x08 */ None,
    /* 0x09 */ None,
    /* 0x0a */ None,
    /* 0x0b */ None,
    /* 0x0c */ None,
    /* 0x0d */ None,
    /* 0x0e */ None,
    /* 0x0f */ None,
    /* 0x10 */ None,
    /* 0x11 */ None,
    /* 0x12 */ None,
    /* 0x13 */ None,
    /* 0x14 */ None,
    /* 0x15 */ None,
    /* 0x16 */ None,
    /* 0x17 */ None,
    /* 0x18 */ None,
    /* 0x19 */ None,
    /* 0x1a */ None,
    /* 0x1b */ None,
    /* 0x1c */ Some(KeyEvent::new(0x1c, Pressed, KeypadEnter)),
    /* 0x1d */ Some(KeyEvent::new(0x1d, Pressed, RightCtrl)),
    /* 0x1e */ None,
    /* 0x1f */ None,
    /* 0x20 */ None,
    /* 0x21 */ None,
    /* 0x22 */ None,
    /* 0x23 */ None,
    /* 0x24 */ None,
    /* 0x25 */ None,
    /* 0x26 */ None,
    /* 0x27 */ None,
    /* 0x28 */ None,
    /* 0x29 */ None,
    /* 0x2a */ None,
    /* 0x2b */ None,
    /* 0x2c */ None,
    /* 0x2d */ None,
    /* 0x2e */ None,
    /* 0x2f */ None,
    /* 0x30 */ None,
    /* 0x31 */ None,
    /* 0x32 */ None,
    /* 0x33 */ None,
    /* 0x34 */ None,
    /* 0x35 */ None,
    /* 0x36 */ None,
    /* 0x37 */ None,
    /* 0x38 */ None,
    /* 0x39 */ None,
    /* 0x3a */ None,
    /* 0x3b */ None,
    /* 0x3c */ None,
    /* 0x3d */ None,
    /* 0x3e */ None,
    /* 0x3f */ None,
    /* 0x40 */ None,
    /* 0x41 */ None,
    /* 0x42 */ None,
    /* 0x43 */ None,
    /* 0x44 */ None,
    /* 0x45 */ None,
    /* 0x46 */ None,
    /* 0x47 */ None,
    /* 0x48 */ Some(KeyEvent::new(0x48, Pressed, ArrowUp)),
    /* 0x49 */ None,
    /* 0x4a */ None,
    /* 0x4b */ Some(KeyEvent::new(0x4b, Pressed, ArrowLeft)),
    /* 0x4c */ None,
    /* 0x4d */ Some(KeyEvent::new(0x4d, Pressed, ArrowRight)),
    /* 0x4e */ None,
    /* 0x4f */ None,
    /* 0x50 */ Some(KeyEvent::new(0x50, Pressed, ArrowDown)),
    /* 0x51 */ None,
    /* 0x52 */ None,
    /* 0x53 */ None,
    /* 0x54 */ None,
    /* 0x55 */ None,
    /* 0x56 */ None,
    /* 0x57 */ None,
    /* 0x58 */ None,
    /* 0x59 */ None,
    /* 0x5a */ None,
    /* 0x5b */ Some(KeyEvent::new(0x5b, Pressed, LeftGui)),
    /* 0x5c */ Some(KeyEvent::new(0x5c, Pressed, RightGui)),
    /* 0x5d */ None,
    /* 0x5e */ None,
    /* 0x5f */ None,
    /* 0x60 */ None,
    /* 0x61 */ None,
    /* 0x62 */ None,
    /* 0x63 */ None,
    /* 0x64 */ None,
    /* 0x65 */ None,
    /* 0x66 */ None,
    /* 0x67 */ None,
    /* 0x68 */ None,
    /* 0x69 */ None,
    /* 0x6a */ None,
    /* 0x6b */ None,
    /* 0x6c */ None,
    /* 0x6d */ None,
    /* 0x6e */ None,
    /* 0x6f */ None,
    /* 0x70 */ None,
    /* 0x71 */ None,
    /* 0x72 */ None,
    /* 0x73 */ None,
    /* 0x74 */ None,
    /* 0x75 */ None,
    /* 0x76 */ None,
    /* 0x77 */ None,
    /* 0x78 */ None,
    /* 0x79 */ None,
    /* 0x7a */ None,
    /* 0x7b */ None,
    /* 0x7c */ None,
    /* 0x7d */ None,
    /* 0x7e */ None,
    /* 0x7f */ None,
    /* 0x80 */ None,
    /* 0x81 */ None,
    /* 0x82 */ None,
    /* 0x83 */ None,
    /* 0x84 */ None,
    /* 0x85 */ None,
    /* 0x86 */ None,
    /* 0x87 */ None,
    /* 0x88 */ None,
    /* 0x89 */ None,
    /* 0x8a */ None,
    /* 0x8b */ None,
    /* 0x8c */ None,
    /* 0x8d */ None,
    /* 0x8e */ None,
    /* 0x8f */ None,
    /* 0x90 */ None,
    /* 0x91 */ None,
    /* 0x92 */ None,
    /* 0x93 */ None,
    /* 0x94 */ None,
    /* 0x95 */ None,
    /* 0x96 */ None,
    /* 0x97 */ None,
    /* 0x98 */ None,
    /* 0x99 */ None,
    /* 0x9a */ None,
    /* 0x9b */ None,
    /* 0x9c */ Some(KeyEvent::new(0x9c, Released, KeypadEnter)),
    /* 0x9d */ Some(KeyEvent::new(0x9c, Released, RightCtrl)),
    /* 0x9e */ None,
    /* 0x9f */ None,
    /* 0xa0 */ None,
    /* 0xa1 */ None,
    /* 0xa2 */ None,
    /* 0xa3 */ None,
    /* 0xa4 */ None,
    /* 0xa5 */ None,
    /* 0xa6 */ None,
    /* 0xa7 */ None,
    /* 0xa8 */ None,
    /* 0xa9 */ None,
    /* 0xaa */ None,
    /* 0xab */ None,
    /* 0xac */ None,
    /* 0xad */ None,
    /* 0xae */ None,
    /* 0xaf */ None,
    /* 0xb0 */ None,
    /* 0xb1 */ None,
    /* 0xb2 */ None,
    /* 0xb3 */ None,
    /* 0xb4 */ None,
    /* 0xb5 */ None,
    /* 0xb6 */ None,
    /* 0xb7 */ None,
    /* 0xb8 */ None,
    /* 0xb9 */ None,
    /* 0xba */ None,
    /* 0xbb */ None,
    /* 0xbc */ None,
    /* 0xbd */ None,
    /* 0xbe */ None,
    /* 0xbf */ None,
    /* 0xc0 */ None,
    /* 0xc1 */ None,
    /* 0xc2 */ None,
    /* 0xc3 */ None,
    /* 0xc4 */ None,
    /* 0xc5 */ None,
    /* 0xc6 */ None,
    /* 0xc7 */ None,
    /* 0xc8 */ Some(KeyEvent::new(0xc8, Released, ArrowUp)),
    /* 0xc9 */ None,
    /* 0xca */ None,
    /* 0xcb */ Some(KeyEvent::new(0xcb, Released, ArrowLeft)),
    /* 0xcc */ None,
    /* 0xcd */ Some(KeyEvent::new(0xcd, Released, ArrowRight)),
    /* 0xce */ None,
    /* 0xcf */ None,
    /* 0xd0 */ Some(KeyEvent::new(0xd0, Released, ArrowDown)),
    /* 0xd1 */ None,
    /* 0xd2 */ None,
    /* 0xd3 */ None,
    /* 0xd4 */ None,
    /* 0xd5 */ None,
    /* 0xd6 */ None,
    /* 0xd7 */ None,
    /* 0xd8 */ None,
    /* 0xd9 */ None,
    /* 0xda */ None,
    /* 0xdb */ Some(KeyEvent::new(0xdb, Released, LeftGui)),
    /* 0xdc */ Some(KeyEvent::new(0xdc, Released, RightGui)),
    /* 0xdd */ None,
    /* 0xde */ None,
    /* 0xdf */ None,
    /* 0xe0 */ None,
    /* 0xe1 */ None,
    /* 0xe2 */ None,
    /* 0xe3 */ None,
    /* 0xe4 */ None,
    /* 0xe5 */ None,
    /* 0xe6 */ None,
    /* 0xe7 */ None,
    /* 0xe8 */ None,
    /* 0xe9 */ None,
    /* 0xea */ None,
    /* 0xeb */ None,
    /* 0xec */ None,
    /* 0xed */ None,
    /* 0xee */ None,
    /* 0xef */ None,
    /* 0xf0 */ None,
    /* 0xf1 */ None,
    /* 0xf2 */ None,
    /* 0xf3 */ None,
    /* 0xf4 */ None,
    /* 0xf5 */ None,
    /* 0xf6 */ None,
    /* 0xf7 */ None,
    /* 0xf8 */ None,
    /* 0xf9 */ None,
    /* 0xfa */ None,
    /* 0xfb */ None,
    /* 0xfc */ None,
    /* 0xfd */ None,
    /* 0xfe */ None,
    /* 0xff */ None,
];
