name: cargo build-kernel && cargo test

on:
    push:
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: Rust project - latest
        runs-on: ubuntu-latest
        container: ghcr.io/kentucky-fried-kernel/kfs-test-runner
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - run: rustup target add x86_64-unknown-none
            - run: rustup default nightly
            - run: rustup component add rust-src
            - run: apt update
            - run: apt install -y make
            - run: apt install -y build-essential
            - run: apt install -y gcc-multilib
            - run: apt install -y qemu-system
            - run: apt install -y grub-common
            - run: apt install -y xorriso
            - run: apt install -y mtools
            - run: grub-install
            - run: make test
