# disabled until #49 is solved
name: cargo build-kernel && cargo test

on:
    push:
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: Rust project - latest
        runs-on: ubuntu-latest
        container: ghcr.io/kentucky-fried-kernel/kfs-test-runner
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - run: rustup target add x86-64-unknown-none
            - run: rustup default nightly
            - run: rustup component add rust-src
            - run: sudo apt install make
            - run: sudo apt install build-essential
            - run: sudo apt install gcc-multilib
            - run: sudo apt install qemu-system
            - run: sudo grub-install
            - run: make test
